services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ticket-booth-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TestAcc@1234"
      MSSQL_PID: "Developer"
    ports: ["1433:1433"]
    volumes:
      - ./Data:/var/opt/mssql
  mssql-tools:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlcmd-client
    depends_on:
      - mssql
    entrypoint: [ "/bin/bash" ]
    tty: true
    # chia sẻ network với mssql để kết nối dễ hơn
    networks:
      - default