services:
  ticket-booth:
    build: ./TicketBooth
    container_name: ticket-booth
    ports: ["8080:8080"]
    volumes:
      - ./ticket-booth/.m2:/root/.m2
      - ./ticket-booth/logs:/app/logs
    depends_on:
      - mssql
    environment:
      - spring.datasource.url=jdbc:sqlserver://mssql:1433;databaseName=TicketBooth;encrypt=false;trustServerCertificate=true
      - spring.datasource.username=SA
      - spring.datasource.password=TestAcc@1234
    networks:
      - default

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ticket-booth-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TestAcc@1234"
      MSSQL_PID: "Developer"
    ports: ["1433:1433"]
    volumes:
      - ./Database:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  mssql-tools:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlcmd-client
    depends_on:
      - mssql
    entrypoint: [ "/bin/bash" ]
    tty: true
    # chia sẻ network với mssql để kết nối dễ hơn
    networks:
      - default

networks:
  default:
