services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ticket-booth-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TestAcc@1234"
      MSSQL_PID: "Developer"
    ports: ["1433:1433"]
    volumes:
      - mssql_data:/var/opt/mssql/database
volumes:
  mssql_data: