# render.yaml
services:
  # 1. Dịch vụ Backend (Ticket Booth App)
  # Đây là dịch vụ web chính, sẽ được truy cập từ bên ngoài.
  - type: web
    name: ticket-booth
    env: docker
    dockerfilePath: ./TicketBooth/Dockerfile # Đường dẫn đến Dockerfile của bạn
    
    # Render tự động phát hiện và mở cổng mà ứng dụng của bạn lắng nghe.
    # Health Check để Render biết khi nào ứng dụng của bạn sẵn sàng.
    healthCheck:
      path: /actuator/health # Thay đổi nếu endpoint của bạn khác
    
    # Khai báo biến môi trường.
    envVars:
      # Render sẽ tự động kết nối service này với service 'mssql' bên dưới.
      - key: spring.datasource.url
        value: jdbc:sqlserver://mssql:1433;databaseName=TicketBooth;encrypt=false;trustServerCertificate=true
      - key: spring.datasource.username
        value: SA
      - key: spring.datasource.password
        # Rất khuyến khích sử dụng Secret File của Render cho mật khẩu!
        # Xem ghi chú về bảo mật bên dưới.
        value: TestAcc@1234

  # 2. Dịch vụ Database (MS SQL Server)
  # Đây là dịch vụ riêng, chỉ có thể được truy cập bởi các dịch vụ khác trong cùng tài khoản.
  - type: priv
    name: mssql
    env: docker
    dockerImage: mcr.microsoft.com/mssql/server:2022-latest
    
    # Khai báo biến môi trường cho MS SQL Server.
    envVars:
      - key: ACCEPT_EULA
        value: "Y"
      - key: SA_PASSWORD
        value: TestAcc@1234 # Nên dùng Secret File!
      - key: MSSQL_PID
        value: "Developer"
        
    # QUAN TRỌNG: Tạo một ổ đĩa bền vững để lưu trữ dữ liệu database.
    # Dữ liệu sẽ không bị mất khi bạn triển khai lại.
    disks:
      - name: mssql-data
        mountPath: /var/opt/mssql # Đây là nơi MS SQL lưu dữ liệu
        sizeGB: 10 # Kích thước khởi tạo, bạn có thể tăng sau này
